# Generated by Django 2.2 on 2020-08-13 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descript', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.FileField(upload_to='')),
                ('label', models.TextField(choices=[('n', 'new'), ('h', 'hot')])),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idsp', models.IntegerField()),
                ('user', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
