# Generated by Django 2.2 on 2020-08-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.CharField(default='quyduong', max_length=255),
            preserve_default=False,
        ),
    ]
