# Generated by Django 2.2 on 2020-08-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='idsp',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
