# Generated by Django 2.2 on 2020-08-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cart_idsp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.TextField(choices=[('n', 'new'), ('h', 'hot')], default='new'),
            preserve_default=False,
        ),
    ]
