# Generated by Django 3.0.8 on 2020-08-13 09:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descript',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
